"""Initial schema.

Written by hand rather than autogenerated, so the optional pgvector extension
and the constraints that carry real meaning are explicit rather than a diff
artefact.

pgvector is created `IF NOT EXISTS` and the embedding column is added only when
the extension actually installed. RAG retrieval degrades to lexical BM25 without
it (see `rag/pipeline.py`), so a managed instance that forbids the extension
still runs the service.

Revision ID: 0001
Revises:
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from tutor_match_meta.repositories.models import SCHEMA

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

JSONB = postgresql.JSONB(astext_type=sa.Text())


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    ]


def upgrade() -> None:
    # We share the demo_command_center database, so every TutorMatch table lives
    # in its own schema. Created first, and IF NOT EXISTS so a re-run is safe.
    if SCHEMA:
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")

    op.create_table(
        "tutor_projection",
        sa.Column("tutor_id", sa.String(128), primary_key=True),
        sa.Column("public_ref", sa.String(256), nullable=False),
        sa.Column("name", sa.String(160), nullable=False),
        sa.Column("gender", sa.String(16)),
        sa.Column("avatar_url", sa.String(512)),
        sa.Column("city", sa.String(80)),
        sa.Column("locality", sa.String(120)),
        sa.Column("district", sa.String(80)),
        sa.Column("state", sa.String(80)),
        sa.Column("pincode", sa.String(12)),
        sa.Column("latitude", sa.Float()),
        sa.Column("longitude", sa.Float()),
        sa.Column("geo_granularity", sa.String(16)),
        sa.Column("subjects", JSONB, nullable=False, server_default="[]"),
        sa.Column("boards", JSONB, nullable=False, server_default="[]"),
        sa.Column("classes", JSONB, nullable=False, server_default="[]"),
        sa.Column("modes", JSONB, nullable=False, server_default="[]"),
        sa.Column("experience_years", sa.Integer()),
        sa.Column("education", sa.String(400)),
        sa.Column("profile_summary", sa.Text()),
        sa.Column("fee_min", sa.Integer()),
        sa.Column("fee_max", sa.Integer()),
        sa.Column("fee_label", sa.String(64)),
        sa.Column("review_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rating_avg", sa.Float()),
        sa.Column("expertise_avg", sa.Float()),
        sa.Column("patience_avg", sa.Float()),
        sa.Column("reliability_avg", sa.Float()),
        sa.Column("communication_avg", sa.Float()),
        sa.Column("latest_review_at", sa.DateTime(timezone=True)),
        sa.Column("active_students", sa.Integer()),
        sa.Column("travel_radius_km", sa.Float()),
        sa.Column("projection_version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("source_updated_at", sa.DateTime(timezone=True)),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_checksum", sa.String(64), nullable=False),
        *_timestamps(),
        sa.CheckConstraint("review_count >= 0", name="ck_tutor_review_count_non_negative"),
        sa.CheckConstraint(
            "rating_avg IS NULL OR (rating_avg >= 0 AND rating_avg <= 5)",
            name="ck_tutor_rating_range",
        ),
        schema=SCHEMA,
    )
    op.create_index("ix_tutor_projection_city", "tutor_projection", ["city"], schema=SCHEMA)
    op.create_index("ix_tutor_projection_pincode", "tutor_projection", ["pincode"], schema=SCHEMA)
    op.create_index("ix_tutor_projection_city_synced", "tutor_projection", ["city", "synced_at"], schema=SCHEMA)
    # Every candidate query filters on freshness before anything else.
    op.create_index("ix_tutor_projection_synced", "tutor_projection", ["synced_at"], schema=SCHEMA)

    op.create_table(
        "tutor_availability",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("tutor_id", sa.String(128), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_minute", sa.Integer(), nullable=False),
        sa.Column("end_minute", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(48), nullable=False, server_default="Asia/Kolkata"),
        sa.Column("source", sa.String(32), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True)),
        *_timestamps(),
        sa.UniqueConstraint("tutor_id", "weekday", "start_minute", name="uq_availability_slot"),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name="ck_availability_weekday"),
        sa.CheckConstraint("end_minute > start_minute", name="ck_availability_order"),
        schema=SCHEMA,
    )
    op.create_index("ix_tutor_availability_tutor_id", "tutor_availability", ["tutor_id"], schema=SCHEMA)

    op.create_table(
        "conversation_state",
        sa.Column("conversation_id", sa.String(128), primary_key=True),
        sa.Column("state", sa.String(32), nullable=False),
        sa.Column("fsm_version", sa.String(8), nullable=False),
        # The optimistic lock. Every UPDATE is conditional on this value.
        sa.Column("lock_version", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("turn_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("history", JSONB, nullable=False, server_default="[]"),
        *_timestamps(),
        schema=SCHEMA,
    )
    op.create_index("ix_conversation_state_state", "conversation_state", ["state"], schema=SCHEMA)

    op.create_table(
        "match_requirement",
        sa.Column("conversation_id", sa.String(128), primary_key=True),
        sa.Column("schema_version", sa.String(8), nullable=False),
        sa.Column("lead_id", sa.String(128)),
        sa.Column("payload", JSONB, nullable=False),
        *_timestamps(),
        schema=SCHEMA,
    )
    op.create_index("ix_match_requirement_lead_id", "match_requirement", ["lead_id"], schema=SCHEMA)

    op.create_table(
        "match_decision",
        sa.Column("match_session_id", sa.String(64), primary_key=True),
        sa.Column("conversation_id", sa.String(128), nullable=False),
        sa.Column("trace_id", sa.String(64), nullable=False),
        sa.Column("policy_id", sa.String(64), nullable=False),
        sa.Column("policy_version", sa.String(16), nullable=False),
        sa.Column("policy_checksum", sa.String(64), nullable=False),
        sa.Column("matched", sa.Boolean(), nullable=False),
        sa.Column("no_match_reason", sa.String(120)),
        sa.Column(
            "requires_human_review", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("candidate_ids", JSONB, nullable=False, server_default="[]"),
        sa.Column("rejections", JSONB, nullable=False, server_default="[]"),
        sa.Column("score_snapshot", JSONB, nullable=False, server_default="[]"),
        sa.Column("shortlist", JSONB, nullable=False, server_default="[]"),
        sa.Column("degraded_sources", JSONB, nullable=False, server_default="[]"),
        sa.Column("oldest_source_data_at", sa.DateTime(timezone=True)),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        *_timestamps(),
        schema=SCHEMA,
    )
    op.create_index("ix_match_decision_conversation_id", "match_decision", ["conversation_id"], schema=SCHEMA)
    op.create_index("ix_match_decision_trace_id", "match_decision", ["trace_id"], schema=SCHEMA)
    op.create_index(
        "ix_decision_conversation_generated",
        "match_decision",
        ["conversation_id", "generated_at"],
        schema=SCHEMA,
    )

    op.create_table(
        "match_feedback",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("match_session_id", sa.String(64), nullable=False),
        sa.Column("tutor_id", sa.String(128), nullable=False),
        sa.Column("outcome", sa.String(32), nullable=False),
        sa.Column("detail", sa.String(400)),
        *_timestamps(),
        sa.UniqueConstraint("match_session_id", "tutor_id", "outcome", name="uq_feedback"),
        schema=SCHEMA,
    )
    op.create_index("ix_match_feedback_session", "match_feedback", ["match_session_id"], schema=SCHEMA)

    op.create_table(
        "idempotency_record",
        sa.Column("key", sa.String(128), primary_key=True),
        sa.Column(
            "claimed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        schema=SCHEMA,
    )
    op.create_index("ix_idempotency_expires", "idempotency_record", ["expires_at"], schema=SCHEMA)

    op.create_table(
        "outbox_event",
        sa.Column("dedup_key", sa.String(128), primary_key=True),
        sa.Column("kind", sa.String(48), nullable=False),
        sa.Column("conversation_id", sa.String(128), nullable=False),
        sa.Column("trace_id", sa.String(64), nullable=False),
        sa.Column("payload", JSONB, nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default="pending"),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("available_at", sa.DateTime(timezone=True)),
        sa.Column("last_error", sa.String(240)),
        sa.Column("delivered_at", sa.DateTime(timezone=True)),
        *_timestamps(),
        sa.CheckConstraint(
            "status IN ('pending','delivered','failed','dead')", name="ck_outbox_status"
        ),
        schema=SCHEMA,
    )
    op.create_index("ix_outbox_status_available", "outbox_event", ["status", "available_at"], schema=SCHEMA)

    op.create_table(
        "approval_request",
        sa.Column("idempotency_key", sa.String(128), primary_key=True),
        sa.Column("command", sa.String(64), nullable=False),
        sa.Column("risk", sa.String(16), nullable=False),
        sa.Column("reason", sa.String(240), nullable=False),
        sa.Column("envelope", JSONB, nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default="pending"),
        sa.Column("approved_by", sa.String(120)),
        sa.Column("approved_at", sa.DateTime(timezone=True)),
        *_timestamps(),
        schema=SCHEMA,
    )
    op.create_index("ix_approval_status", "approval_request", ["status"], schema=SCHEMA)

    op.create_table(
        "llm_usage",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("trace_id", sa.String(64), nullable=False),
        sa.Column("conversation_hash", sa.String(64), nullable=False),
        sa.Column("provider", sa.String(32), nullable=False),
        sa.Column("model", sa.String(64), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(64), nullable=False),
        sa.Column("prompt_version", sa.String(32), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("completion_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cost_micros", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("latency_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("error_code", sa.String(64)),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        schema=SCHEMA,
    )
    op.create_index("ix_llm_usage_trace", "llm_usage", ["trace_id"], schema=SCHEMA)
    op.create_index("ix_llm_usage_created", "llm_usage", ["created_at"], schema=SCHEMA)

    op.create_table(
        "geo_point",
        sa.Column("key", sa.String(160), primary_key=True),
        sa.Column("granularity", sa.String(16), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("source", sa.String(32), nullable=False),
        *_timestamps(),
        schema=SCHEMA,
    )

    op.create_table(
        "rag_document",
        sa.Column("document_id", sa.String(128), primary_key=True),
        sa.Column("title", sa.String(240), nullable=False),
        sa.Column("source", sa.String(240), nullable=False),
        sa.Column("document_version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("checksum", sa.String(64), nullable=False),
        sa.Column("sensitivity", sa.String(24), nullable=False, server_default="public"),
        sa.Column("access_scope", JSONB, nullable=False, server_default="[]"),
        sa.Column("effective_from", sa.DateTime(timezone=True)),
        sa.Column("effective_to", sa.DateTime(timezone=True)),
        sa.Column("superseded", sa.Boolean(), nullable=False, server_default=sa.false()),
        *_timestamps(),
        schema=SCHEMA,
    )

    op.create_table(
        "rag_chunk",
        sa.Column("chunk_id", sa.String(160), primary_key=True),
        sa.Column("document_id", sa.String(128), nullable=False),
        sa.Column("document_version", sa.Integer(), nullable=False),
        sa.Column("chunk_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(64), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("sensitivity", sa.String(24), nullable=False, server_default="public"),
        sa.Column("access_scope", JSONB, nullable=False, server_default="[]"),
        sa.Column("embedding_model", sa.String(64)),
        *_timestamps(),
        sa.UniqueConstraint("document_id", "document_version", "chunk_number", name="uq_chunk"),
        schema=SCHEMA,
    )
    op.create_index("ix_rag_chunk_document", "rag_chunk", ["document_id"], schema=SCHEMA)
    # Ingest-time deduplication is a checksum lookup.
    op.create_index("ix_rag_chunk_checksum", "rag_chunk", ["checksum"], schema=SCHEMA)

    op.create_table(
        "sync_checkpoint",
        sa.Column("name", sa.String(64), primary_key=True),
        sa.Column("last_offset", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_run_at", sa.DateTime(timezone=True)),
        sa.Column("last_success_at", sa.DateTime(timezone=True)),
        sa.Column("rows_processed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_error", sa.String(240)),
        *_timestamps(),
        # This `schema=` was missing. `migrations/env.py` does not set a
        # search_path, so the table was created in the connection's default
        # schema (`public`) while `Base.metadata` declares it in `tutor_match`
        # — so every ORM query for it read `tutor_match.sync_checkpoint` and
        # got "relation does not exist". The incremental projection sync would
        # have failed on its first run and every run after, the projection
        # would never refresh, and 24 hours later the freshness alarm would
        # fire with no tutor recommendable. Asserted now by
        # tests/unit/test_migrations.py.
        schema=SCHEMA,
    )

    _add_pgvector_if_available()


def _add_pgvector_if_available() -> None:
    """Add the embedding column only when the extension actually installed.

    `CREATE EXTENSION` can fail on a managed instance without superuser, so it
    is attempted and then *verified* rather than assumed. Without pgvector, RAG
    retrieval runs on lexical BM25 and the service is fully functional.

    The attempt itself is wrapped in an exception handler. It previously was
    not: a bare `op.execute("CREATE EXTENSION …")` raises on a restricted role,
    which aborts the whole migration **after** fourteen tables have been
    created — leaving a half-built schema and an `alembic_version` that does
    not describe it. The verification below was already correct; only the
    attempt was unguarded.
    """
    qualified = f"{SCHEMA}.rag_chunk" if SCHEMA else "rag_chunk"
    op.execute(
        """
        DO $ext$
        BEGIN
            CREATE EXTENSION IF NOT EXISTS vector;
        EXCEPTION
            WHEN insufficient_privilege OR feature_not_supported THEN
                RAISE NOTICE 'pgvector unavailable to this role; '
                             'RAG will use lexical retrieval';
        END
        $ext$;
        """
    )
    op.execute(
        f"""
        DO $do$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
                ALTER TABLE {qualified} ADD COLUMN IF NOT EXISTS embedding vector(1536);
                CREATE INDEX IF NOT EXISTS ix_rag_chunk_embedding
                    ON {qualified} USING ivfflat (embedding vector_cosine_ops)
                    WITH (lists = 100);
            END IF;
        END
        $do$;
        """
    )


def downgrade() -> None:
    # Manual only. The safety gate blocks destructive statements in the
    # automated pipeline, and only inspects `upgrade()`.
    for table in (
        "rag_chunk",
        "rag_document",
        "sync_checkpoint",
        "geo_point",
        "llm_usage",
        "approval_request",
        "outbox_event",
        "idempotency_record",
        "match_feedback",
        "match_decision",
        "match_requirement",
        "conversation_state",
        "tutor_availability",
        "tutor_projection",
    ):
        op.drop_table(table, schema=SCHEMA)
