"""Generate the local `.env` for TutorMatch and the paired section for Lead Intake.

Reads the shared infrastructure values out of the Lead Intake `.env` (the same
RDS instance, the same OpenAI account, the same WhatsApp number) and mints fresh
secrets for everything that is TutorMatch-specific.

The paired secrets — `INTERNAL_SECRET` — are written to **both** files with the
same value, because that is the shared secret on the handoff. Everything else is
generated per service.

Both `.env` files are gitignored. This script never prints a secret and never
overwrites a value that already exists in the Lead Intake file.

    uv run python scripts/generate_env.py            # write both
    uv run python scripts/generate_env.py --dry-run  # show what would change
"""

from __future__ import annotations

import argparse
import secrets
import sys
import urllib.parse as urlparse
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
PRODUCTION_AGENTS = HERE.parent
LEAD_INTAKE_ENV = PRODUCTION_AGENTS / "nxtutors-lead-intake-agent" / ".env"
DEMO_CC_ENV = PRODUCTION_AGENTS / "Demo Command Center Agent" / ".env"
TUTOR_MATCH_ENV = HERE / ".env"

SECTION_HEADER = "# ===== NXTUTORS TUTOR INTELLIGENCE (tutor-match-meta) ====="


def read_env(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip()
    return values


def hex_secret(nbytes: int = 32) -> str:
    return secrets.token_hex(nbytes)


def derive_postgres_dsn(demo_cc: dict[str, str], lead: dict[str, str]) -> str:
    """Reuse the Demo Command Center database and its application user.

    Preferred over minting a new database because those credentials already
    exist, already have the right grants, and are already reachable from the
    same VPC. TutorMatch keeps its tables in a dedicated **schema**
    (`TMM_POSTGRES_SCHEMA`), so the two services share a database without
    sharing a namespace — including `alembic_version`, which is one row per
    schema and would otherwise have two services fighting over one head.
    """
    dsn = demo_cc.get("DATABASE_URL", "")
    if dsn.startswith("postgresql"):
        # Already `postgresql+asyncpg://…` in the Demo CC env.
        return dsn
    # Fall back to assembling it from the discrete DEMO_COMMAND_CENTER_DB_* keys.
    host = demo_cc.get("DEMO_COMMAND_CENTER_DB_HOST", "")
    if host:
        user = demo_cc.get("DEMO_COMMAND_CENTER_DB_USERNAME", "postgres")
        password = urlparse.quote(demo_cc.get("DEMO_COMMAND_CENTER_DB_PASSWORD", ""), safe="")
        port = demo_cc.get("DEMO_COMMAND_CENTER_DB_PORT", "5432")
        database = demo_cc.get("DEMO_COMMAND_CENTER_DB_DATABASE", "demo_command_center")
        return f"postgresql+asyncpg://{user}:{password}@{host}:{port}/{database}"
    # Last resort: the Lead Intake instance, converted to asyncpg.
    lead_dsn = lead.get("DATABASE_URL", "")
    if not lead_dsn:
        return "postgresql+asyncpg://tmm:tmm@localhost:5433/tmm"
    parsed = urlparse.urlparse(lead_dsn)
    userinfo = parsed.username or "postgres"
    if parsed.password:
        userinfo = f"{userinfo}:{urlparse.quote(parsed.password, safe='')}"
    port = f":{parsed.port}" if parsed.port else ""
    return f"postgresql+asyncpg://{userinfo}@{parsed.hostname}{port}/tutormatch"


def build_tutor_match_env(lead: dict[str, str], demo_cc: dict[str, str], shared_secret: str) -> str:
    """A lean `.env`: section headers, no prose.

    The reasoning behind each value lives in docs/ and in the `Settings`
    docstrings, not in the file people scan for a hostname.
    """
    openai_key = lead.get("OPENAI_API_KEY", "")
    return f"""# tutor-match-meta - local. Generated by scripts/generate_env.py. Gitignored.

# --- runtime
TMM_ENVIRONMENT=local
TMM_SERVICE_NAME=tutor-match-meta
TMM_LOG_LEVEL=INFO
TMM_DEFAULT_TIMEZONE=Asia/Kolkata

# --- postgres (Demo Command Center database, dedicated schema)
TMM_POSTGRES_DSN={derive_postgres_dsn(demo_cc, lead)}
TMM_POSTGRES_SCHEMA=tutor_match
TMM_POSTGRES_REQUIRE_TLS={str(demo_cc.get("DB_REQUIRE_TLS", "true")).lower()}
TMM_POSTGRES_POOL_SIZE=5
TMM_POSTGRES_MAX_OVERFLOW=0
TMM_POSTGRES_STATEMENT_TIMEOUT_MS=5000

# --- handoff (paired with TUTOR_MATCHING_AGENT_INTERNAL_SECRET in lead-intake)
TMM_INTERNAL_SECRET={shared_secret}
TMM_CONTINUATION_SIGNING_KEY={hex_secret()}
TMM_CONTINUATION_TTL_SECONDS=21600
TMM_OUTBOUND_OWNERSHIP=caller_sends
TMM_ACCOUNT_REQUIRED_FOR_MATCH=false

# --- rollout (shadow=true means compute, record, stay silent)
TMM_FLAG_ENABLED=true
TMM_FLAG_SHADOW_MODE=true
TMM_FLAG_PERCENTAGE_ROLLOUT=0
TMM_FLAG_LLM_ENABLED=true
TMM_FLAG_WRITEBACK_ENABLED=false
TMM_FLAG_RAG_ENABLED=false
TMM_FLAG_MEMORY_ENABLED=false
TMM_FLAG_AUTO_DEMO_ENABLED=false
TMM_FLAG_ALWAYS_ON_REFS=

# --- security
TMM_INGRESS_SIGNING_KEY={hex_secret()}
TMM_INGRESS_TIMESTAMP_TOLERANCE_SECONDS=300
TMM_INGRESS_MAX_BODY_BYTES=65536
TMM_RATE_LIMIT_PER_CONVERSATION_PER_MINUTE=12
TMM_RATE_LIMIT_GLOBAL_PER_MINUTE=600
TMM_HASH_PEPPER={hex_secret()}

# --- website read (signed HTTPS tutor feed; no second database)
TMM_TUTOR_FEED_PAGE_SIZE=100
TMM_TUTOR_FEED_TIMEOUT_SECONDS=15.0
TMM_WEBSITE_API_BASE_URL=
TMM_WEBSITE_API_SIGNING_KEY={hex_secret()}
TMM_WEBSITE_API_TIMEOUT_SECONDS=8.0

# --- website write-back
TMM_WEBSITE_WRITE_ENABLED=false

# --- chitragupta
TMM_CHITRAGUPTA_ENABLED=false
TMM_CHITRAGUPTA_BASE_URL=
TMM_CHITRAGUPTA_API_KEY=
TMM_CHITRAGUPTA_AGENT_ID=tutor-match-meta
TMM_CHITRAGUPTA_TIMEOUT_SECONDS=3.0

# --- whatsapp (off: lead-intake sends our replies)
TMM_WHATSAPP_ENABLED=false
TMM_WHATSAPP_PHONE_NUMBER_ID={lead.get("WHATSAPP_PHONE_NUMBER_ID", "")}
TMM_WHATSAPP_ACCESS_TOKEN=
TMM_WHATSAPP_API_VERSION={lead.get("WHATSAPP_GRAPH_API_VERSION", "v21.0")}

# --- llm
TMM_LLM_PROVIDER={"openai" if openai_key else "stub"}
TMM_OPENAI_API_KEY={openai_key}
TMM_OPENAI_BASE_URL=
TMM_LLM_TIER1_MODEL={lead.get("OPENAI_MODEL_FAST", "gpt-4o-mini")}
TMM_LLM_TIER2_MODEL={lead.get("OPENAI_MODEL_STRONG", "gpt-4o")}
TMM_LLM_TIMEOUT_SECONDS=12.0
TMM_LLM_MAX_RETRIES=2
TMM_LLM_MAX_OUTPUT_TOKENS=800
TMM_LLM_CONVERSATION_TOKEN_BUDGET=40000
TMM_LLM_STORE_RESPONSES=false

# --- aws
TMM_AWS_REGION={lead.get("AWS_REGION", "ap-south-1")}
TMM_MATCH_QUEUE_URL=
TMM_OUTBOUND_QUEUE_URL=
TMM_ANALYTICS_BUCKET=
TMM_SECRETS_PREFIX=/tutor-match-meta/

# --- cache
TMM_CACHE_BACKEND=memory
TMM_REDIS_URL={demo_cc.get("REDIS_URL", "") or lead.get("REDIS_URL", "")}
TMM_CACHE_DEFAULT_TTL_SECONDS=300

# --- geocoding
TMM_GEOCODER=offline
TMM_GEOCODER_BASE_URL=
TMM_GEOCODER_API_KEY=

# --- policy
TMM_POLICY_DIR=config/policies
TMM_DEFAULT_POLICY=regular_school_support.v1
TMM_PROJECTION_FRESH_HOURS=6
TMM_PROJECTION_AGING_HOURS=24

# --- links
TMM_WEBSITE_PUBLIC_BASE_URL=https://www.nxtutors.com
"""


def build_lead_intake_section(shared_secret: str, existing: dict[str, str]) -> str:
    """The block appended to the Lead Intake `.env`. Adds keys, never rewrites."""
    local_url = "http://localhost:8081/internal/v1/handoff"
    return f"""

{SECTION_HEADER}
# TutorMatch is called as an internal handoff and returns {{"status","reply_text"}}.
# Lead Intake keeps the Meta webhook and the outbound sender.
# TUTOR_MATCHING_AGENT_INTERNAL_SECRET needs a Settings field in app/core/config.py.
TUTOR_MATCHING_AGENT_WEBHOOK_URL={existing.get("TUTOR_MATCHING_AGENT_WEBHOOK_URL") or local_url}
TUTOR_MATCHING_AGENT_INTERNAL_SECRET={shared_secret}
TUTOR_MATCHING_AGENT_TIMEOUT_S=2.0

# Enable when ready to route live traffic (TutorMatch still ships in shadow mode).
# INTEGRATIONS_ENABLED=true
# INTEGRATION_MODE=webhook
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--force", action="store_true", help="overwrite an existing TutorMatch .env"
    )
    args = parser.parse_args()

    lead = read_env(LEAD_INTAKE_ENV)
    if not lead:
        print(f"WARNING: no Lead Intake .env at {LEAD_INTAKE_ENV}; using placeholders")

    existing_tm = read_env(TUTOR_MATCH_ENV)
    # Reuse the shared secret if one side already has it, so re-running does not
    # silently break a working pairing.
    shared_secret = (
        existing_tm.get("TMM_INTERNAL_SECRET")
        or lead.get("TUTOR_MATCHING_AGENT_INTERNAL_SECRET")
        or hex_secret()
    )

    demo_cc = read_env(DEMO_CC_ENV)
    if not demo_cc:
        print(f"WARNING: no Demo Command Center .env at {DEMO_CC_ENV}")
    tm_content = build_tutor_match_env(lead, demo_cc, shared_secret)
    if TUTOR_MATCH_ENV.exists() and not args.force and not args.dry_run:
        print(f"SKIP  {TUTOR_MATCH_ENV.name} already exists (use --force to regenerate)")
    elif args.dry_run:
        print(f"WOULD WRITE  {TUTOR_MATCH_ENV}  ({len(tm_content.splitlines())} lines)")
    else:
        TUTOR_MATCH_ENV.write_text(tm_content, encoding="utf-8")
        print(f"WROTE {TUTOR_MATCH_ENV}")

    lead_text = (
        LEAD_INTAKE_ENV.read_text(encoding="utf-8", errors="replace")
        if LEAD_INTAKE_ENV.is_file()
        else ""
    )
    if SECTION_HEADER in lead_text:
        print("SKIP  Lead Intake .env already has the TutorMatch section")
    elif not LEAD_INTAKE_ENV.is_file():
        print(f"SKIP  {LEAD_INTAKE_ENV} not found")
    elif args.dry_run:
        print(f"WOULD APPEND section to {LEAD_INTAKE_ENV}")
    else:
        LEAD_INTAKE_ENV.write_text(
            lead_text.rstrip("\n") + build_lead_intake_section(shared_secret, lead),
            encoding="utf-8",
        )
        print(f"APPENDED TutorMatch section to {LEAD_INTAKE_ENV}")

    print("\nBoth files are gitignored. No secret was printed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
