"""Regenerate `.env.example` from the `Settings` model.

`.env.example` is the only documentation of what this service can be
configured with, and it had drifted badly: 35 settings missing, and one key
(`TMM_REDIS_URL`) that was never a `Settings` field at all — so it looked
configured, did nothing, and carried a live credential shape.

Generating it removes the drift by construction. Run it after adding or
removing a setting; `make check` fails if the file is stale.

    python scripts/sync_env_example.py          # rewrite
    python scripts/sync_env_example.py --check  # fail if stale (CI)

Secrets are emitted as empty placeholders. This file is committed, so it must
never contain a value.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from pydantic import SecretStr

from tutor_match_meta.config.settings import Settings

TARGET = Path(__file__).resolve().parents[1] / ".env.example"

HEADER = """\
# tutor-match-meta — every supported setting.
#
# GENERATED by scripts/sync_env_example.py from config/settings.py.
# Do not edit by hand: add the field to Settings and re-run the script.
# `make check` fails when this file is out of date.
#
# Secrets are blank on purpose. This file is committed.
"""

#: Ordered groups. A setting not matched by any prefix lands in "other", which
#: is a prompt to classify it rather than a place for it to live.
GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "runtime and network placement",
        ("environment", "service_name", "log_level", "default_timezone", "network_zone"),
    ),
    ("postgres — the system of record", ("postgres_",)),
    (
        "handoff with lead intake",
        ("internal_secret", "continuation_", "outbound_ownership", "account_required"),
    ),
    ("rollout flags", ("flag_",)),
    ("security and rate limits", ("ingress_", "rate_limit_", "hash_pepper")),
    ("website read (signed HTTPS tutor feed)", ("tutor_feed_", "website_api_")),
    ("website write-back", ("website_write", "website_direct")),
    ("chitragupta memory", ("chitragupta_",)),
    ("whatsapp outbound", ("whatsapp_",)),
    (
        "llm provider and model routing",
        (
            "llm_provider",
            "openai_",
            "llm_tier",
            "model_",
            "llm_timeout",
            "llm_max_retries",
            "llm_max_output",
            "llm_store",
        ),
    ),
    (
        "token and call budgets",
        ("llm_conversation_token_budget", "llm_max_calls", "llm_max_escalations", "rag_"),
    ),
    (
        "aws",
        (
            "aws_",
            "enrich_queue",
            "match_queue",
            "outbound_queue",
            "analytics_bucket",
            "secrets_prefix",
        ),
    ),
    ("cache and kill switches", ("cache_", "kill_switch_")),
    ("geocoding", ("geocod", "geo_")),
    ("scoring policy and freshness", ("policy_", "default_policy", "projection_")),
    ("analytics", ("analytics_enabled", "analytics_include")),
    ("public links", ("website_public",)),
)

SECRET_HINT = ("key", "token", "secret", "pepper", "dsn", "password")


def default_for(name: str, field: object) -> str:
    annotation = getattr(field, "annotation", None)
    default = getattr(field, "default", None)

    if annotation is SecretStr or isinstance(default, SecretStr):
        return ""
    if any(hint in name for hint in SECRET_HINT):
        return ""
    if default is None:
        return ""
    if isinstance(default, bool):
        return "true" if default else "false"
    if hasattr(default, "value"):  # StrEnum
        return str(default.value)
    return str(default)


def render() -> str:
    remaining = dict(Settings.model_fields)
    lines: list[str] = [HEADER]

    for title, prefixes in GROUPS:
        names = [n for n in remaining if any(n.startswith(p) for p in prefixes)]
        if not names:
            continue
        lines.append(f"\n# --- {title}")
        for name in sorted(names):
            lines.append(f"TMM_{name.upper()}={default_for(name, remaining.pop(name))}")

    if remaining:
        lines.append("\n# --- other (unclassified: add a group in sync_env_example.py)")
        for name in sorted(remaining):
            lines.append(f"TMM_{name.upper()}={default_for(name, remaining[name])}")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    rendered = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""

    if args.check:
        if current != rendered:
            print(".env.example is out of date. Run: python scripts/sync_env_example.py")
            return 1
        print(f".env.example is current ({len(Settings.model_fields)} settings)")
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET.name} — {len(Settings.model_fields)} settings")
    return 0


if __name__ == "__main__":
    sys.exit(main())
